branches:
  only:
    - master

skip_tags: true
max_jobs: 1

# Build worker image (VM template)
image: 
  - Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - C:\Python37-x64\python -m pip install -r requirements.txt

environment:
  matrix:
    - AIRFLOW_GPL_UNIDECODE: 1

cache:
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - make test_av
